#!/bin/bash

# Script to launch audio servers for music-making.

case $1 in

  start )
    echo Starting fluidsynth...

    # Start fluidsynth
    tmux new-[window -- 'fluidsynth --server --no-shell -p "fluidsynth 1" --audio-driver=jack \
        --connect-jack-outputs --reverb=0 --chorus=0 --gain=0.8 \
        -o midi.autoconnect=false \
        /usr/share/sounds/sf2/FluidR3_GM.sf2 \
        &>/tmp/fluidsynth.out'

    sleep 1

    if pgrep -l jackd && pgrep -l fluidsynth
    then
      echo Audio servers running.
    else
      echo There was a problem starting the audio servers.
    fi

    ;;

  stop )
    killall fluidsynth
    killall jackd
    echo Audio servers stopped.
    ;;

  * )
    echo Please specify start or stop...
    ;;
esac
